-- ============================================================================
-- Chaos Engineering Platform - Observability & Experiment Data Repository
-- ============================================================================
-- Industry Standard Schema for:
-- 1. Baseline metrics storage (time-series partitioning)
-- 2. Experiment execution tracking (audit trail)
-- 3. Experiment results and evidence (DORA compliance)
-- 4. SLO definitions and tracking
--
-- Design Principles:
-- - Immutable audit trail for compliance (DORA, SOX, HIPAA)
-- - Time-series optimization (partitioning by date)
-- - Referential integrity (foreign keys)
-- - Performance (indexes on common queries)
-- - Retention policies (configurable data retention)
-- ============================================================================

-- Create dedicated schema for chaos engineering platform
CREATE SCHEMA IF NOT EXISTS chaos_platform;

-- ============================================================================
-- BASELINE & STEADY STATE TABLES
-- ============================================================================

-- Services: Registry of all monitored services
CREATE TABLE IF NOT EXISTS chaos_platform.services (
    service_id SERIAL PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    environment VARCHAR(50) DEFAULT 'production',  -- production, staging, dev
    team_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Baseline Metrics: Statistical summaries of steady state
-- Typically created by SteadyStateAnalyzer (Step 1 of 6-step workflow)
CREATE TABLE IF NOT EXISTS chaos_platform.baseline_metrics (
    baseline_id SERIAL PRIMARY KEY,
    service_id INTEGER NOT NULL REFERENCES chaos_platform.services(service_id),
    metric_name VARCHAR(255) NOT NULL,
    
    -- Statistical summaries
    mean_value NUMERIC(12, 4),
    median_value NUMERIC(12, 4),
    stddev_value NUMERIC(12, 4),
    min_value NUMERIC(12, 4),
    max_value NUMERIC(12, 4),
    
    -- Percentiles
    p50 NUMERIC(12, 4),
    p95 NUMERIC(12, 4),
    p99 NUMERIC(12, 4),
    
    -- Anomaly detection bounds (mean ± n*sigma)
    lower_bound_2sigma NUMERIC(12, 4),
    upper_bound_2sigma NUMERIC(12, 4),
    upper_bound_3sigma NUMERIC(12, 4),
    
    -- Metadata
    analysis_period_days INTEGER DEFAULT 14,
    sample_count BIGINT,
    data_completeness_percent NUMERIC(5, 2),
    
    -- Time tracking
    analysis_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Versioning (for regression detection)
    version INTEGER DEFAULT 1,
    is_active BOOLEAN DEFAULT true,
    
    UNIQUE(service_id, metric_name, analysis_date, version)
);

-- SLO Targets: Service Level Objectives derived from baselines
-- Generated by SteadyStateAnalyzer alongside baselines
CREATE TABLE IF NOT EXISTS chaos_platform.slo_targets (
    slo_id SERIAL PRIMARY KEY,
    service_id INTEGER NOT NULL REFERENCES chaos_platform.services(service_id),
    metric_name VARCHAR(255) NOT NULL,
    metric_type VARCHAR(50),  -- latency, throughput, error_rate, etc.
    
    -- SLO definition
    target_value NUMERIC(12, 4),  -- e.g., 100ms for P99 latency
    threshold_type VARCHAR(50),  -- max, min, range
    threshold_lower NUMERIC(12, 4),
    threshold_upper NUMERIC(12, 4),
    
    -- SLO parameters
    confidence_level_percent NUMERIC(5, 2) DEFAULT 99.0,
    safety_margin_percent NUMERIC(5, 2) DEFAULT 10.0,
    
    -- Time tracking
    analysis_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT true,
    
    UNIQUE(service_id, metric_name, analysis_date)
);

-- Service Topology: Service dependency graph
-- Generated by SteadyStateAnalyzer
CREATE TABLE IF NOT EXISTS chaos_platform.service_topology (
    topology_id SERIAL PRIMARY KEY,
    source_service_id INTEGER NOT NULL REFERENCES chaos_platform.services(service_id),
    target_service_id INTEGER NOT NULL REFERENCES chaos_platform.services(service_id),
    
    -- Dependency metrics
    avg_latency_ms NUMERIC(12, 4),
    call_count_daily BIGINT,
    error_rate_percent NUMERIC(5, 2),
    is_critical_path BOOLEAN DEFAULT false,
    is_spof BOOLEAN DEFAULT false,  -- Single Point of Failure
    
    -- Time tracking
    analysis_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- EXPERIMENT TRACKING TABLES
-- ============================================================================

-- Experiments: Chaos experiment definitions and execution tracking
-- References mcp-test-postgres-pool-exhaustion.json experiments
CREATE TABLE IF NOT EXISTS chaos_platform.experiments (
    experiment_id INTEGER PRIMARY KEY,  -- Stable ID from experiment_metadata_control (UUID v5)
    experiment_name VARCHAR(255) NOT NULL,
    experiment_file VARCHAR(255),  -- JSON file path
    service_id INTEGER NOT NULL REFERENCES chaos_platform.services(service_id),
    
    -- Experiment metadata
    description TEXT,
    chaos_scenario VARCHAR(255),  -- e.g., "connection_pool_exhaustion"
    team_name VARCHAR(255),
    
    -- Execution tracking
    status VARCHAR(50) DEFAULT 'pending',  -- pending, running, completed, failed
    scheduled_start_time TIMESTAMP,
    actual_start_time TIMESTAMP,
    actual_end_time TIMESTAMP,
    duration_seconds INTEGER,
    
    -- User tracking (for audit trail)
    created_by VARCHAR(255) DEFAULT 'system',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Compliance flags
    requires_evidence BOOLEAN DEFAULT true,
    dora_relevant BOOLEAN DEFAULT true,
    
    UNIQUE(experiment_name, created_at)
);

-- Experiment Runs: Individual execution records
-- Immutable audit trail for each experiment execution
CREATE TABLE IF NOT EXISTS chaos_platform.experiment_runs (
    run_id SERIAL PRIMARY KEY,
    experiment_id INTEGER NOT NULL REFERENCES chaos_platform.experiments(experiment_id),
    
    -- Run metadata
    run_number INTEGER NOT NULL,  -- 1st, 2nd, 3rd run of this experiment
    status VARCHAR(50) NOT NULL DEFAULT 'running',  -- running, aborted, ended, failed
    
    -- Experiment Metrics Scores (calculated by metrics_calculator_control)
    risk_score INTEGER DEFAULT 0,           -- 0-255: Risk assessment score
    complexity_score INTEGER DEFAULT 0,     -- 0-255: Complexity assessment
    test_quality INTEGER DEFAULT 0,         -- 0-255: Test quality score
    risk_level VARCHAR(50),                 -- low, medium, high, critical
    success_rate NUMERIC(5, 2),             -- 0-100: Percentage of actions completed
    
    -- Timing
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    steady_state_check_start TIMESTAMP,
    chaos_injection_start TIMESTAMP,
    chaos_injection_end TIMESTAMP,
    recovery_check_end TIMESTAMP,
    
    -- Results (populated after completion)
    steady_state_passed BOOLEAN,
    experiment_completed BOOLEAN,
    recovery_successful BOOLEAN,
    
    -- Results summary and metadata (JSON)
    result_summary JSONB,           -- Summary of results as JSON
    metadata JSONB,                 -- Additional metadata as JSON
    
    -- Metadata
    executed_by VARCHAR(255) DEFAULT 'system',
    environment VARCHAR(50),  -- production, staging, dev
    
    -- Immutable (for audit)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    UNIQUE(experiment_id, run_number)
);

-- ============================================================================
-- METRICS SNAPSHOTS (Time-Series Data)
-- ============================================================================

-- Metric Snapshots: Captured at different phases (pre, during, post chaos)
-- Partitioned by date for performance
CREATE TABLE IF NOT EXISTS chaos_platform.metric_snapshots (
    snapshot_id SERIAL PRIMARY KEY,
    run_id INTEGER NOT NULL REFERENCES chaos_platform.experiment_runs(run_id),
    service_id INTEGER NOT NULL REFERENCES chaos_platform.services(service_id),
    
    -- Phase information
    phase VARCHAR(50) NOT NULL,  -- pre_chaos, during_chaos, post_chaos
    phase_sequence INTEGER,  -- 1, 2, 3 for ordering
    
    -- Metric data (jsonb for flexibility with different metric types)
    metrics JSONB NOT NULL,  -- { "metric_name": value, ... }
    
    -- Individual metric columns for common metrics (optimization)
    connection_count INTEGER,
    query_latency_ms NUMERIC(12, 4),
    error_rate_percent NUMERIC(5, 2),
    throughput_rps NUMERIC(12, 4),
    cpu_percent NUMERIC(5, 2),
    memory_percent NUMERIC(5, 2),
    
    -- Time tracking
    captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for time-series queries
CREATE INDEX idx_metric_snapshots_run_phase ON chaos_platform.metric_snapshots(run_id, phase, captured_at);
CREATE INDEX idx_metric_snapshots_service_date ON chaos_platform.metric_snapshots(service_id, DATE(captured_at));

-- ============================================================================
-- ANALYSIS & RESULTS TABLES
-- ============================================================================

-- Experiment Analysis: Post-experiment analysis and RCA
-- Immutable record for compliance evidence
CREATE TABLE IF NOT EXISTS chaos_platform.experiment_analysis (
    analysis_id SERIAL PRIMARY KEY,
    run_id INTEGER NOT NULL REFERENCES chaos_platform.experiment_runs(run_id),
    
    -- Impact assessment
    max_deviation_sigma NUMERIC(12, 4),
    max_degradation_percent NUMERIC(5, 2),
    affected_metrics TEXT[],  -- Array of metric names affected
    
    -- Recovery metrics
    recovery_time_seconds INTEGER,
    full_recovery_achieved BOOLEAN,
    partial_recovery_metrics TEXT[],
    
    -- Anomalies detected
    anomaly_count INTEGER DEFAULT 0,
    anomalies JSONB,  -- Detailed anomaly records
    
    -- RCA (Root Cause Analysis)
    rca_findings TEXT[],
    root_causes JSONB,  -- Structured RCA data
    
    -- Recommendations
    recommendations TEXT[],
    remediation_priority VARCHAR(50),  -- critical, high, medium, low
    
    -- Compliance evidence
    compliance_status VARCHAR(50),  -- pass, warning, fail
    dora_evidence JSONB,  -- DORA-specific evidence
    
    -- Analysis metadata
    analysis_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    analyzed_by VARCHAR(255) DEFAULT 'system',
    
    -- Immutable audit trail
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(run_id)
);

-- Experiment Test Metrics: Metrics tested in each experiment
-- Created by metrics_calculator_control during experiment initialization
CREATE TABLE IF NOT EXISTS chaos_platform.experiment_test_metrics (
    test_metric_id SERIAL PRIMARY KEY,
    run_id INTEGER NOT NULL REFERENCES chaos_platform.experiment_runs(run_id),
    
    -- Metric identification
    metric_name VARCHAR(255) NOT NULL,           -- e.g., 'postgresql_backends', 'chaos_db_query_latency_ms'
    metric_query TEXT,                           -- PromQL query used
    
    -- Metric severity/importance
    criticality VARCHAR(50) DEFAULT 'medium',    -- low, medium, high, critical
    threshold_sigma INTEGER DEFAULT 2,           -- tolerance level in standard deviations
    
    -- Audit
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Composite index for efficient queries
    UNIQUE(run_id, metric_name)
);

-- Create indexes for common queries
CREATE INDEX idx_experiment_test_metrics_run ON chaos_platform.experiment_test_metrics(run_id);
CREATE INDEX idx_experiment_test_metrics_criticality ON chaos_platform.experiment_test_metrics(criticality);

-- ============================================================================
-- AUDIT & COMPLIANCE TABLES
-- ============================================================================

-- Audit Trail: Immutable log of all actions (for compliance)
CREATE TABLE IF NOT EXISTS chaos_platform.audit_log (
    log_id SERIAL PRIMARY KEY,
    
    -- Action information
    action VARCHAR(255) NOT NULL,  -- created_baseline, executed_experiment, etc.
    entity_type VARCHAR(100),  -- experiment, baseline, run, etc.
    entity_id INTEGER,
    
    -- User/system information
    actor VARCHAR(255),  -- user or system
    actor_type VARCHAR(50),  -- human, system, automation
    
    -- Details
    details JSONB,
    
    -- Timestamp (immutable)
    action_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for audit queries
CREATE INDEX idx_audit_log_entity ON chaos_platform.audit_log(entity_type, entity_id, action_timestamp);

-- ============================================================================
-- VIEWS FOR COMMON QUERIES
-- ============================================================================

-- Latest Baselines: Most recent baseline for each service/metric
CREATE OR REPLACE VIEW chaos_platform.v_latest_baselines AS
SELECT DISTINCT ON (b.service_id, b.metric_name)
    s.service_name,
    b.metric_name,
    b.mean_value,
    b.stddev_value,
    b.p99,
    b.upper_bound_2sigma,
    b.upper_bound_3sigma,
    b.analysis_date,
    b.created_at
FROM chaos_platform.baseline_metrics b
JOIN chaos_platform.services s ON b.service_id = s.service_id
WHERE b.is_active = true
ORDER BY b.service_id, b.metric_name, b.analysis_date DESC;

-- Recent Experiments: Last 30 experiments with status
CREATE OR REPLACE VIEW chaos_platform.v_recent_experiments AS
SELECT 
    e.experiment_id,
    e.experiment_name,
    s.service_name,
    e.chaos_scenario,
    e.status,
    COUNT(er.run_id) as total_runs,
    SUM(CASE WHEN er.status = 'completed' THEN 1 ELSE 0 END) as successful_runs,
    MAX(er.end_time) as last_run_time,
    e.created_at
FROM chaos_platform.experiments e
LEFT JOIN chaos_platform.experiment_runs er ON e.experiment_id = er.experiment_id
JOIN chaos_platform.services s ON e.service_id = s.service_id
WHERE e.created_at > NOW() - INTERVAL '30 days'
GROUP BY e.experiment_id, e.experiment_name, s.service_name, e.chaos_scenario, e.status, e.created_at
ORDER BY e.created_at DESC;

-- Compliance Status: Summary of compliance across recent experiments
CREATE OR REPLACE VIEW chaos_platform.v_compliance_summary AS
SELECT 
    s.service_name,
    COUNT(DISTINCT er.run_id) as total_runs,
    SUM(CASE WHEN ea.compliance_status = 'pass' THEN 1 ELSE 0 END) as passed_runs,
    SUM(CASE WHEN ea.compliance_status = 'warning' THEN 1 ELSE 0 END) as warning_runs,
    SUM(CASE WHEN ea.compliance_status = 'fail' THEN 1 ELSE 0 END) as failed_runs,
    ROUND(100.0 * SUM(CASE WHEN ea.compliance_status = 'pass' THEN 1 ELSE 0 END) / COUNT(DISTINCT er.run_id), 2) as pass_rate
FROM chaos_platform.services s
LEFT JOIN chaos_platform.experiments e ON s.service_id = e.service_id
LEFT JOIN chaos_platform.experiment_runs er ON e.experiment_id = er.experiment_id
LEFT JOIN chaos_platform.experiment_analysis ea ON er.run_id = ea.run_id
WHERE er.end_time > NOW() - INTERVAL '30 days'
GROUP BY s.service_name
ORDER BY s.service_name;

-- ============================================================================
-- INITIAL DATA
-- ============================================================================

-- Create initial services
INSERT INTO chaos_platform.services (service_name, description, environment, team_name)
VALUES 
    ('postgres', 'PostgreSQL Database Service', 'production', 'Infrastructure'),
    ('order-service', 'Order Processing Service', 'production', 'Backend'),
    ('payment-service', 'Payment Processing Service', 'production', 'Backend'),
    ('inventory-service', 'Inventory Management Service', 'production', 'Backend'),
    ('api-gateway', 'API Gateway Service', 'production', 'Platform'),
    ('notification-service', 'Notification Service', 'production', 'Backend')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- RETENTION & MAINTENANCE
-- ============================================================================

-- Function to clean up old audit logs (keep 365 days)
CREATE OR REPLACE FUNCTION chaos_platform.cleanup_old_audit_logs()
RETURNS void AS $$
DELETE FROM chaos_platform.audit_log
WHERE action_timestamp < NOW() - INTERVAL '365 days';
$$ LANGUAGE SQL;

-- Function to archive old experiment runs (optional, mark as archived)
CREATE OR REPLACE FUNCTION chaos_platform.archive_old_runs()
RETURNS void AS $$
UPDATE chaos_platform.experiment_runs
SET status = 'archived'
WHERE end_time < NOW() - INTERVAL '180 days'
AND status = 'completed';
$$ LANGUAGE SQL;

-- ============================================================================
-- GRANTS & SECURITY
-- ============================================================================

-- Create role for chaos platform application
DO
$$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'chaos_app') THEN
        CREATE ROLE chaos_app WITH LOGIN PASSWORD 'chaos_app_secure_password';
    END IF;
END
$$;

-- Create role for chaos experiments (used by CLI and automation)
DO
$$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'chaos_user') THEN
        CREATE ROLE chaos_user WITH LOGIN PASSWORD 'chaos_password';
    END IF;
END
$$;

-- Grant permissions to chaos_app role
GRANT USAGE ON SCHEMA chaos_platform TO chaos_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA chaos_platform TO chaos_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA chaos_platform TO chaos_app;

-- For audit trail: allow inserts but not deletes
GRANT INSERT ON chaos_platform.audit_log TO chaos_app;

-- ============================================================================
-- AUDIT & REPORTING VIEWS
-- ============================================================================

-- Experiment Runs Summary View
-- Shows all experiment runs with complete metadata and scores in separate columns
CREATE OR REPLACE VIEW chaos_platform.experiment_runs_summary AS
SELECT
    er.run_id,
    er.experiment_id,
    e.experiment_name,
    s.service_id,
    s.service_name,
    er.run_number,
    er.status,
    er.start_time,
    er.end_time,
    er.risk_score,
    er.complexity_score,
    er.test_quality,
    er.risk_level,
    er.success_rate,
    er.steady_state_passed,
    er.experiment_completed,
    er.recovery_successful,
    er.result_summary,
    er.metadata,
    er.executed_by,
    er.environment,
    er.created_at
FROM
    chaos_platform.experiment_runs er
    JOIN chaos_platform.experiments e ON er.experiment_id = e.experiment_id
    JOIN chaos_platform.services s ON e.service_id = s.service_id
ORDER BY
    er.start_time DESC;

-- Experiment Audit Trail View
-- Shows complete audit log entries with experiment context
CREATE OR REPLACE VIEW chaos_platform.experiment_audit_trail AS
SELECT
    al.log_id,
    al.entity_type,
    al.entity_id AS run_id,
    er.experiment_id,
    e.experiment_name,
    COALESCE(al.details->>'title', e.experiment_name) AS experiment_title,
    s.service_name,
    er.run_number,
    al.action AS audit_action,
    al.details AS audit_details,
    al.actor AS audit_actor,
    al.action_timestamp AS audit_timestamp
FROM
    chaos_platform.audit_log al
    LEFT JOIN chaos_platform.experiment_runs er ON al.entity_id = er.run_id AND al.entity_type = 'experiment_run'
    LEFT JOIN chaos_platform.experiments e ON er.experiment_id = e.experiment_id
    LEFT JOIN chaos_platform.services s ON e.service_id = s.service_id
WHERE
    al.entity_type = 'experiment_run'
ORDER BY
    al.action_timestamp DESC;

-- Latest Experiment Runs View
-- Shows only the most recent run for each experiment
CREATE OR REPLACE VIEW chaos_platform.latest_experiment_runs AS
SELECT DISTINCT ON (er.experiment_id)
    er.run_id,
    er.experiment_id,
    e.experiment_name,
    s.service_name,
    er.run_number,
    er.status,
    er.start_time,
    er.end_time,
    er.risk_score,
    er.complexity_score,
    er.test_quality,
    er.risk_level,
    er.success_rate,
    er.steady_state_passed
FROM
    chaos_platform.experiment_runs er
    JOIN chaos_platform.experiments e ON er.experiment_id = e.experiment_id
    JOIN chaos_platform.services s ON e.service_id = s.service_id
ORDER BY
    er.experiment_id,
    er.start_time DESC;

-- Grant view permissions after views are created
GRANT SELECT ON chaos_platform.experiment_runs_summary TO chaos_app;
GRANT SELECT ON chaos_platform.experiment_audit_trail TO chaos_app;
GRANT SELECT ON chaos_platform.latest_experiment_runs TO chaos_app;

-- Grant permissions to chaos_user role (same as chaos_app)
GRANT USAGE ON SCHEMA chaos_platform TO chaos_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA chaos_platform TO chaos_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA chaos_platform TO chaos_user;
GRANT INSERT ON chaos_platform.audit_log TO chaos_user;
GRANT SELECT ON chaos_platform.experiment_runs_summary TO chaos_user;
GRANT SELECT ON chaos_platform.experiment_audit_trail TO chaos_user;
GRANT SELECT ON chaos_platform.latest_experiment_runs TO chaos_user;

COMMIT;
